language: go
go:
  - 1.8.x

cache:
  directories:
    - $HOME/gopath/pkg

notifications:
  webhooks: http://twbot-180547646.us-east-1.elb.amazonaws.com:8182/travis/buildstatus
  email: false

install:
  - mv $HOME/gopath/src/github.com/Teamwork $HOME/gopath/src/github.com/teamwork
  - go get -u github.com/golang/dep/cmd/dep
  - cd $HOME/gopath/src/github.com/teamwork/middleware
  - dep ensure
  - go get -u gopkg.in/alecthomas/gometalinter.v1 && gometalinter.v1 --install

script:
  - cd $HOME/gopath/src/github.com/teamwork/middleware

  - go test -race -cover -covermode=set -coverprofile=coverage.txt && bash <(curl -s https://codecov.io/bash)
  - gometalinter.v1 --config .linter_test.json
  - gometalinter.v1 --config .linter.json
