language: go
go:
  - 1.9.x
go_import_path: github.com/teamwork/middleware
notifications:
  email: false
  webhooks: http://tw-bot.teamworkops.com:8182/travis/buildstatus
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/middleware
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
