language: go
go:
  - 1.9.x
cache:
  directories:
    - $HOME/gopath/pkg
install:
  - ./bin/setup-travis
script:
  - cd $HOME/gopath/src/github.com/teamwork/middleware
  - ./bin/test
  - ./bin/coverage
  - ./bin/lint
